// Ma'at's Scale - Field Classification Patterns

import type { FieldPattern, FieldType } from './types.js';

const emptyPattern = (fieldType: FieldType): FieldPattern => ({
  fieldType,
  selectors: [],
  labelPatterns: [],
  namePatterns: [],
  ariaPatterns: [],
  placeholderPatterns: [],
});

export const FIELD_PATTERNS: Record<FieldType, FieldPattern> = {
  fullName: {
    fieldType: 'fullName',
    selectors: ['[name*="full_name" i]', '[name*="fullname" i]'],
    labelPatterns: [/^full\s*name$/i, /^your\s*name$/i],
    namePatterns: [/full.*name/i],
    ariaPatterns: [/full.*name/i],
    placeholderPatterns: [/enter.*full.*name/i],
  },
  firstName: {
    fieldType: 'firstName',
    selectors: ['[name*="first_name" i]', '[name*="firstname" i]'],
    labelPatterns: [/^first\s*name$/i],
    namePatterns: [/first.*name/i],
    ariaPatterns: [/first.*name/i],
    placeholderPatterns: [/first\s*name/i],
  },
  lastName: {
    fieldType: 'lastName',
    selectors: ['[name*="last_name" i]', '[name*="lastname" i]'],
    labelPatterns: [/^last\s*name$/i],
    namePatterns: [/last.*name/i],
    ariaPatterns: [/last.*name/i],
    placeholderPatterns: [/last\s*name/i],
  },
  email: {
    fieldType: 'email',
    selectors: ['input[type="email"]', '[name*="email" i]'],
    labelPatterns: [/^email$/i],
    namePatterns: [/email/i],
    ariaPatterns: [/email/i],
    placeholderPatterns: [/email/i, /@/],
  },
  phone: {
    fieldType: 'phone',
    selectors: ['input[type="tel"]', '[name*="phone" i]'],
    labelPatterns: [/^phone$/i],
    namePatterns: [/phone/i],
    ariaPatterns: [/phone/i],
    placeholderPatterns: [/\d{3}[-.]?\d{3}[-.]?\d{4}/],
  },
  address: emptyPattern('address'),
  city: {
    fieldType: 'city',
    selectors: ['[name*="city" i]'],
    labelPatterns: [/^city$/i],
    namePatterns: [/city/i],
    ariaPatterns: [/city/i],
    placeholderPatterns: [/city/i],
  },
  state: {
    fieldType: 'state',
    selectors: ['[name*="state" i]'],
    labelPatterns: [/^state$/i],
    namePatterns: [/state/i],
    ariaPatterns: [/state/i],
    placeholderPatterns: [/state/i],
  },
  zipCode: {
    fieldType: 'zipCode',
    selectors: ['[name*="zip" i]'],
    labelPatterns: [/^zip$/i],
    namePatterns: [/zip/i],
    ariaPatterns: [/zip/i],
    placeholderPatterns: [/\d{5}/],
  },
  country: {
    fieldType: 'country',
    selectors: ['[name*="country" i]'],
    labelPatterns: [/^country$/i],
    namePatterns: [/country/i],
    ariaPatterns: [/country/i],
    placeholderPatterns: [/country/i],
  },
  linkedIn: {
    fieldType: 'linkedIn',
    selectors: ['[name*="linkedin" i]'],
    labelPatterns: [/^linkedin$/i],
    namePatterns: [/linkedin/i],
    ariaPatterns: [/linkedin/i],
    placeholderPatterns: [/linkedin\.com/i],
  },
  website: emptyPattern('website'),
  company: {
    fieldType: 'company',
    selectors: ['[name*="company" i]'],
    labelPatterns: [/^company$/i],
    namePatterns: [/company/i],
    ariaPatterns: [/company/i],
    placeholderPatterns: [/company/i],
  },
  jobTitle: {
    fieldType: 'jobTitle',
    selectors: ['[name*="title" i]'],
    labelPatterns: [/^job\s*title$/i, /^title$/i],
    namePatterns: [/title/i],
    ariaPatterns: [/job.*title/i],
    placeholderPatterns: [/title/i],
  },
  startDate: emptyPattern('startDate'),
  endDate: emptyPattern('endDate'),
  current: emptyPattern('current'),
  jobDescription: emptyPattern('jobDescription'),
  school: emptyPattern('school'),
  degree: emptyPattern('degree'),
  fieldOfStudy: emptyPattern('fieldOfStudy'),
  graduationDate: emptyPattern('graduationDate'),
  gpa: emptyPattern('gpa'),
  coverLetter: emptyPattern('coverLetter'),
  resumeUpload: {
    fieldType: 'resumeUpload',
    selectors: ['input[type="file"]', '[name*="resume" i][type="file"]'],
    labelPatterns: [/^resume$/i],
    namePatterns: [/resume/i],
    ariaPatterns: [/resume/i],
    placeholderPatterns: [],
  },
  salaryExpectations: emptyPattern('salaryExpectations'),
  availability: emptyPattern('availability'),
  authorizedToWork: emptyPattern('authorizedToWork'),
  visaSponsorship: emptyPattern('visaSponsorship'),
  referralSource: emptyPattern('referralSource'),
  unknown: {
    fieldType: 'unknown',
    selectors: [],
    labelPatterns: [],
    namePatterns: [],
    ariaPatterns: [],
    placeholderPatterns: [],
  },
};

export function getPattern(fieldType: FieldType): FieldPattern {
  return FIELD_PATTERNS[fieldType] || FIELD_PATTERNS.unknown;
}
